.TH "xsocket Directory Reference" 3 "Fri Mar 3 2017" "Version 2.0" "XSocket API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xsocket Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBXaccept\&.c\fP"
.br
.RI "\fI\fBXaccept()\fP, \fBXaccept4()\fP - accept/reject jobs sent to a destination\&. \fP"
.ti -1c
.RI "file \fBXbind\&.c\fP"
.br
.RI "\fI\fBXbind()\fP - bind a name to a socket\&. \fP"
.ti -1c
.RI "file \fBXclose\&.c\fP"
.br
.RI "\fI\fBXclose()\fP - close a socket\&. \fP"
.ti -1c
.RI "file \fBXconnect\&.c\fP"
.br
.RI "\fI\fBXconnect()\fP - initiate a connection on a socket\&. \fP"
.ti -1c
.RI "file \fBXdefaultInterface\&.c\fP"
.br
.ti -1c
.RI "file \fBXfcntl\&.c\fP"
.br
.RI "\fI\fBXfcntl()\fP - manipulate a socket\&. \fP"
.ti -1c
.RI "file \fBXfork\&.c\fP"
.br
.RI "\fI\fBXfork()\fP - create a child process\&. \fP"
.ti -1c
.RI "file \fBXgetaddrinfo\&.c\fP"
.br
.RI "\fI\fBXgetaddrinfo()\fP, \fBXfreeaddrinfo()\fP, \fBXgai_strerror()\fP - network address and service translation\&. \fP"
.ti -1c
.RI "file \fBXgetDAGbyName\&.c\fP"
.br
.RI "\fI\fBXgetDAGbyName()\fP, \fBXgetNamebyDAG()\fP, \fBXregisterName()\fP, \fBXgetpeername()\fP, \fBXgetsockname()\fP, \fBxia_ntop()\fP, \fBxia_pton()\fP - network address management\&. \fP"
.ti -1c
.RI "file \fBXgethostname\&.c\fP"
.br
.RI "\fI\fBXgethostname()\fP - get XIA host name\&. \fP"
.ti -1c
.RI "file \fBXgetifaddrs\&.c\fP"
.br
.RI "\fI\fBXgetifaddrs()\fP, \fBXfreeifaddrs()\fP - get interface addresses\&. \fP"
.ti -1c
.RI "file \fBXkeys\&.c\fP"
.br
.RI "\fI\fBXmakeNewSID()\fP, \fBXremoveSID()\fP, \fBXcreateFID()\fP, \fBXremoveFID()\fP -- create/delete cryptographic SIDs & FIDs\&. \fP"
.ti -1c
.RI "file \fBXlisten\&.c\fP"
.br
.RI "\fI\fBXlisten()\fP - listen for connections on a socket\&. \fP"
.ti -1c
.RI "file \fBXmsg\&.c\fP"
.br
.RI "\fI\fBXrecvmsg()\fP, \fBXsendmsg()\fP - send/receive a message on a socket\&. \fP"
.ti -1c
.RI "file \fBXnotify\&.c\fP"
.br
.RI "\fI\fBXnotify()\fP - get notification of network changes\&. \fP"
.ti -1c
.RI "file \fBXrecv\&.c\fP"
.br
.RI "\fI\fBXrecv()\fP, \fBXrecvfrom()\fP - receive a message from a socket\&. \fP"
.ti -1c
.RI "file \fBXselect\&.c\fP"
.br
.RI "\fI\fBXselect()\fP, \fBXpoll()\fP - synchronous I/O multiplexing\&. \fP"
.ti -1c
.RI "file \fBXsend\&.c\fP"
.br
.RI "\fI\fBXsend()\fP, \fBXsendto()\fP - - send a message on a socket\&. \fP"
.ti -1c
.RI "file \fBXsetsockopt\&.c\fP"
.br
.RI "\fI\fBXsetsockopt()\fP,X getsockopt() - get and set options on sockets\&. \fP"
.ti -1c
.RI "file \fBXsocket\&.c\fP"
.br
.RI "\fI\fBXsocket()\fP - create a socket\&. \fP"
.ti -1c
.RI "file \fBXupdateDAG\&.c\fP"
.br
.RI "\fIImplements \fBXreadLocalHostAddr()\fP \fP"
.in -1c
