.TH "include/click Directory Reference" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/click Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBarchive\&.hh\fP"
.br
.RI "\fIClass for handling 'ar' archives\&. \fP"
.ti -1c
.RI "file \fBatomic\&.hh\fP"
.br
.RI "\fIAn atomic 32-bit integer\&. \fP"
.ti -1c
.RI "file \fBbigint\&.hh\fP"
.br
.RI "\fISimple multiple-precision integer arithmetic\&. \fP"
.ti -1c
.RI "file \fBbitvector\&.hh\fP"
.br
.RI "\fIClick's bitvector class\&. \fP"
.ti -1c
.RI "file \fBclp\&.h\fP"
.br
.RI "\fIFunctions for parsing command line options\&. \fP"
.ti -1c
.RI "file \fBconfparse\&.hh\fP"
.br
.RI "\fISupport for parsing configuration strings\&. \fP"
.ti -1c
.RI "file \fBelement\&.hh\fP"
.br
.RI "\fIClick's \fBElement\fP class\&. \fP"
.ti -1c
.RI "file \fBelemfilter\&.hh\fP"
.br
.RI "\fIFilter predicates for elements and ports\&. \fP"
.ti -1c
.RI "file \fBerror\&.hh\fP"
.br
.RI "\fIFlexible error handling classes\&. \fP"
.ti -1c
.RI "file \fBetheraddress\&.hh\fP"
.br
.RI "\fIThe \fBEtherAddress\fP type for Ethernet addresses\&. \fP"
.ti -1c
.RI "file \fBewma\&.hh\fP"
.br
.RI "\fIClick's classes for supporting exponentially weighted moving averages\&. \fP"
.ti -1c
.RI "file \fBgaprate\&.hh\fP"
.br
.RI "\fIA Click helper class for implementing a uniform rate\&. \fP"
.ti -1c
.RI "file \fBhandler\&.hh\fP"
.br
.RI "\fIThe \fBHandler\fP class for router handlers\&. \fP"
.ti -1c
.RI "file \fBhandlercall\&.hh\fP"
.br
.RI "\fIThe \fBHandlerCall\fP helper class for simplifying access to handlers\&. \fP"
.ti -1c
.RI "file \fBhashtable\&.hh\fP"
.br
.RI "\fIClick's hash table container template\&. \fP"
.ti -1c
.RI "file \fBintegers\&.hh\fP"
.br
.RI "\fIFunctions for manipulating integers\&. \fP"
.ti -1c
.RI "file \fBipaddress\&.hh\fP"
.br
.RI "\fIThe \fBIPAddress\fP type for IPv4 addresses\&. \fP"
.ti -1c
.RI "file \fBlist\&.hh\fP"
.br
.RI "\fIClick's doubly-linked list container template\&. \fP"
.ti -1c
.RI "file \fBnameinfo\&.hh\fP"
.br
.RI "\fIClick databases for names, such as IP addresses and services\&. \fP"
.ti -1c
.RI "file \fBnotifier\&.hh\fP"
.br
.RI "\fISupport for activity signals\&. \fP"
.ti -1c
.RI "file \fBpacket\&.hh\fP"
.br
.RI "\fIThe \fBPacket\fP class models packets in Click\&. \fP"
.ti -1c
.RI "file \fBrouter\&.hh\fP"
.br
.RI "\fIThe \fBRouter\fP class implementing a router configuration\&. \fP"
.ti -1c
.RI "file \fBrouterthread\&.hh\fP"
.br
.RI "\fIThe \fBRouterThread\fP class implementing the Click driver loop\&. \fP"
.ti -1c
.RI "file \fBroutervisitor\&.hh\fP"
.br
.RI "\fI\fBRouter\fP configuration visitors for finding elements and ports\&. \fP"
.ti -1c
.RI "file \fBstraccum\&.hh\fP"
.br
.RI "\fIClick's \fBStringAccum\fP class, used to construct Strings efficiently from pieces\&. \fP"
.ti -1c
.RI "file \fBstring\&.hh\fP"
.br
.RI "\fIClick's \fBString\fP class\&. \fP"
.ti -1c
.RI "file \fBsync\&.hh\fP"
.br
.RI "\fIClasses for synchronizing among multiple CPUs, particularly in the Linux kernel\&. \fP"
.ti -1c
.RI "file \fBtask\&.hh\fP"
.br
.RI "\fISupport for \fBTask\fP, which triggers execution frequently\&. \fP"
.ti -1c
.RI "file \fBtimer\&.hh\fP"
.br
.RI "\fISupport for \fBTimer\fP, which triggers execution at a given time\&. \fP"
.ti -1c
.RI "file \fBtimestamp\&.hh\fP"
.br
.RI "\fIThe \fBTimestamp\fP class represents a moment or interval in time\&. \fP"
.ti -1c
.RI "file \fBtokenbucket\&.hh\fP"
.br
.RI "\fIToken bucket rate limiter templates\&. \fP"
.ti -1c
.RI "file \fBtype_traits\&.hh\fP"
.br
.RI "\fIType traits structures\&. \fP"
.ti -1c
.RI "file \fBvector\&.hh\fP"
.br
.RI "\fIClick's vector container template\&. \fP"
.ti -1c
.RI "file \fBxiaheader\&.hh\fP"
.br
.RI "\fIThe \fBPacket\fP class models packets in Click\&. \fP"
.ti -1c
.RI "file \fBxid\&.hh\fP"
.br
.RI "\fI\fBXID\fP addresses\&. \fP"
.in -1c
