.TH "AnyArg" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnyArg \- Parser class that accepts any argument\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <args\&.hh>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBparse\fP (const \fBString\fP &, const \fBArgContext\fP &=blank_args)"
.br
.ti -1c
.RI "static bool \fBparse\fP (const \fBString\fP &str, \fBString\fP &result, const \fBArgContext\fP &=blank_args)"
.br
.ti -1c
.RI "static bool \fBparse\fP (const \fBString\fP &str, \fBVector\fP< \fBString\fP > &result, const \fBArgContext\fP &=blank_args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Parser class that accepts any argument\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
