.TH "include/click/archive.hh" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/click/archive.hh \- Class for handling 'ar' archives\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <click/string\&.hh>\fP
.br
\fC#include <click/vector\&.hh>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBArchiveElement\fP"
.br
.RI "\fIMember of an 'ar' archive\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Class for handling 'ar' archives\&. 

> 
.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
