.TH "include/click/bigint.hh" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/click/bigint.hh \- Simple multiple-precision integer arithmetic\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <click/integers\&.hh>\fP
.br
\fC#include <click/type_traits\&.hh>\fP
.br
\fC#include <click/string\&.hh>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBigint< L, Lhalf >\fP"
.br
.RI "\fITemplate for multiple-precision integer arithmetic\&. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBBigint\fP< uint32_t > \fBbigint\fP"
.br
.RI "\fITypical \fBBigint\fP usage with uint32_t limb_type\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Simple multiple-precision integer arithmetic\&. 

> 
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBBigint\fP<uint32_t> \fBbigint\fP"

.PP
Typical \fBBigint\fP usage with uint32_t limb_type\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
