.TH "BoolArg" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BoolArg \- Parser class for booleans\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <args\&.hh>\fP
.PP
Inherited by DefaultArg< bool >\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBparse\fP (const \fBString\fP &str, bool &result, const \fBArgContext\fP &args=blank_args)"
.br
.ti -1c
.RI "static \fBString\fP \fBunparse\fP (bool x)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Parser class for booleans\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
