.TH "char_array< S >" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
char_array< S > \- Template defining a fixed-size character array\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <type_traits\&.hh>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBx\fP [S]"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<size_t S>
.br
class char_array< S >"
Template defining a fixed-size character array\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
