.TH "conditional< B, T, F >" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
conditional< B, T, F > \- Conditional type transformation\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <type_traits\&.hh>\fP
.SH "Detailed Description"
.PP 

.SS "template<bool B, typename T, typename F>
.br
class conditional< B, T, F >"
Conditional type transformation\&. 

If B is true, then conditional<B, T, F>::type is equivalent to T\&. Otherwise, it is equivalent to F\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
