.TH "include/dagaddr.hpp" 3 "Fri Mar 3 2017" "Version 2.0" "XSocket API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/dagaddr.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <unistd\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br
\fC#include <map>\fP
.br
\fC#include 'xia\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBNode\fP"
.br
.ti -1c
.RI "class \fBGraph\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPATH_SIZE\fP   4096"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PATH_SIZE   4096"

.SH "Author"
.PP 
Generated automatically by Doxygen for XSocket API from the source code\&.
