.TH "dagaddr/cpp/dagaddr.cpp" 3 "Fri Mar 3 2017" "Version 2.0" "XSocket API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dagaddr/cpp/dagaddr.cpp \- Implements dagaddr library\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'dagaddr\&.hpp'\fP
.br
\fC#include 'utils\&.hpp'\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <map>\fP
.br
\fC#include <stack>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <netinet/in\&.h>\fP
.br
\fC#include <arpa/inet\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <execinfo\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for XSocket API from the source code\&.
