.TH "Deque_iterator< T >" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Deque_iterator< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <deque\&.hh>\fP
.PP
Inherits Deque_const_iterator< T >\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBDeque\fP< T >::size_type \fBsize_type\fP"
.br
.ti -1c
.RI "typedef Deque_const_iterator< T > \fBconst_iterator\fP"
.br
.ti -1c
.RI "typedef \fBDeque_iterator\fP< T > \fBiterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDeque_iterator\fP (\fBDeque\fP< T > *q, int p)"
.br
.ti -1c
.RI "T * \fBoperator\->\fP () const "
.br
.ti -1c
.RI "T & \fBoperator*\fP () const "
.br
.ti -1c
.RI "T & \fBoperator[]\fP (int n) const "
.br
.ti -1c
.RI "\fBiterator\fP & \fBoperator+=\fP (size_type n)"
.br
.ti -1c
.RI "\fBiterator\fP & \fBoperator\-=\fP (size_type n)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class Deque_iterator< T >"
never 

.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
