.TH "do_nothing< T, void >" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
do_nothing< T, void > \- Unary function object that does nothing when called\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <algorithm\&.hh>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef T \fBargument_type\fP"
.br
.ti -1c
.RI "typedef void \fBresult_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBoperator()\fP (const T &)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
struct do_nothing< T, void >"
Unary function object that does nothing when called\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
