.TH "do_nothing< T, U >" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
do_nothing< T, U > \- Binary function object that does nothing when called\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <algorithm\&.hh>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef T \fBfirst_argument_type\fP"
.br
.ti -1c
.RI "typedef U \fBsecond_argument_type\fP"
.br
.ti -1c
.RI "typedef void \fBresult_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBoperator()\fP (const T &, const U &)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T, typename U>
.br
struct do_nothing< T, U >"
Binary function object that does nothing when called\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
