.TH "DoubleArg" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DoubleArg \- Parser class for double-precision floating point numbers\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <args\&.hh>\fP
.PP
Inherits \fBNumArg\fP\&.
.PP
Inherited by DefaultArg< double >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBparse\fP (const \fBString\fP &str, double &result, const \fBArgContext\fP &args=blank_args)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBstatus\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Parser class for double-precision floating point numbers\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
