.TH "ElementCastArg" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ElementCastArg \- Parser class for elements of type \fIt\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <args\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBElementCastArg\fP (const char *t)"
.br
.ti -1c
.RI "bool \fBparse\fP (const \fBString\fP &str, \fBElement\fP *&result, const \fBArgContext\fP &args)"
.br
.ti -1c
.RI "template<typename T > bool \fBparse\fP (const \fBString\fP &str, T *&result, const \fBArgContext\fP &args)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Parser class for elements of type \fIt\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
