.TH "include/click/elemfilter.hh" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/click/elemfilter.hh \- Filter predicates for elements and ports\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <click/element\&.hh>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBElementFilter\fP"
.br
.RI "\fIBase class for filter predicates for elements and ports\&. \fP"
.ti -1c
.RI "class \fBCastElementFilter\fP"
.br
.RI "\fICast-based filter predicate for elements\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Filter predicates for elements and ports\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
