.TH "ElementArg" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ElementArg \- Parser class for elements\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <args\&.hh>\fP
.PP
Inherited by DefaultArg< Element * >\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBparse\fP (const \fBString\fP &str, \fBElement\fP *&result, const \fBArgContext\fP &args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Parser class for elements\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
