.TH "include/click/element.hh" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/click/element.hh \- Click's \fBElement\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <click/glue\&.hh>\fP
.br
\fC#include <click/vector\&.hh>\fP
.br
\fC#include <click/string\&.hh>\fP
.br
\fC#include <click/packet\&.hh>\fP
.br
\fC#include <click/handler\&.hh>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBElement\fP"
.br
.RI "\fIBase class for Click elements\&. \fP"
.ti -1c
.RI "class \fBElement::Port\fP"
.br
.RI "\fIAn \fBElement\fP's ports\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPORT_ASSIGN\fP(o)   (void) (o)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Click's \fBElement\fP class\&. 

> 
.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
