.TH "include/click/etheraddress.hh" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/click/etheraddress.hh \- The \fBEtherAddress\fP type for Ethernet addresses\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <click/string\&.hh>\fP
.br
\fC#include <click/glue\&.hh>\fP
.br
\fC#include <click/type_traits\&.hh>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEtherAddress\fP"
.br
.RI "\fIAn Ethernet address\&. \fP"
.ti -1c
.RI "class \fBEtherAddressArg\fP"
.br
.RI "\fIParser class for Ethernet addresses\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBStringAccum\fP & \fBoperator<<\fP (\fBStringAccum\fP &, const \fBEtherAddress\fP &)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "class \fBEtherAddress\fP \fBCLICK_SIZE_PACKED_ATTRIBUTE\fP"
.br
.ti -1c
.RI "const \fBArgContext\fP \fBblank_args\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBEtherAddress\fP type for Ethernet addresses\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
