.TH "false_type" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
false_type \- Type wrapper for the constant false\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <type_traits\&.hh>\fP
.PP
Inherited by has_fast_int_multiply< T >, \fBhas_trivial_copy< T >\fP, and \fBis_reference< T >\fP\&.
.SH "Detailed Description"
.PP 
Type wrapper for the constant false\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
