.TH "include/click/gaprate.hh" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/click/gaprate.hh \- A Click helper class for implementing a uniform rate\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <click/timestamp\&.hh>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGapRate\fP"
.br
.RI "\fIA helper class for implementing a uniform rate\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A Click helper class for implementing a uniform rate\&. 

> 
.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
