.TH "include/click/handlercall.hh" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/click/handlercall.hh \- The \fBHandlerCall\fP helper class for simplifying access to handlers\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <click/router\&.hh>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHandlerCall\fP"
.br
.RI "\fIConvenience class for calling handlers\&. \fP"
.ti -1c
.RI "class \fBHandlerCallArg\fP"
.br
.RI "\fIParser class for handler call specifications\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBString\fP \fBcp_expand\fP (const \fBString\fP &str, const VariableExpander &env, bool expand_quote, int depth)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBHandlerCall\fP helper class for simplifying access to handlers\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
