.TH "integral_constant< T, V >" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
integral_constant< T, V > \- Type wrapper for an integral constant V\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <type_traits\&.hh>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBintegral_constant\fP< T, V > \fBtype\fP"
.br
.ti -1c
.RI "typedef T \fBvalue_type\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr T \fBvalue\fP = V"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T, T V>
.br
class integral_constant< T, V >"
Type wrapper for an integral constant V\&. 

Offers the following members:
.PP
.IP "\fBtype \fP" 1c
The type itself\&. 
.IP "\fBvalue_type \fP" 1c
The type argument T\&. 
.IP "\fBvalue \fP" 1c
The value argument V\&. 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
