.TH "IP6PrefixArg" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IP6PrefixArg \- Parser class for IPv6 address prefixes\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ip6address\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIP6PrefixArg\fP (bool allow_bare_address_=false)"
.br
.ti -1c
.RI "bool \fBparse\fP (const \fBString\fP &str, IP6Address &addr, int &prefix_len, const \fBArgContext\fP &args=blank_args) const "
.br
.ti -1c
.RI "bool \fBparse\fP (const \fBString\fP &str, IP6Address &addr, IP6Address &prefix, const \fBArgContext\fP &args=blank_args) const "
.br
.ti -1c
.RI "bool \fBparse\fP (const \fBString\fP &str, struct in6_addr &addr, struct in6_addr &prefix, const \fBArgContext\fP &args=blank_args) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBallow_bare_address\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Parser class for IPv6 address prefixes\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
