.TH "include/click/ipaddress.hh" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/click/ipaddress.hh \- The \fBIPAddress\fP type for IPv4 addresses\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <click/string\&.hh>\fP
.br
\fC#include <click/glue\&.hh>\fP
.br
\fC#include <click/type_traits\&.hh>\fP
.br
\fC#include <clicknet/ip\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBVector< T >\fP"
.br
.RI "\fI\fBVector\fP template\&. \fP"
.ti -1c
.RI "class \fBIPAddress\fP"
.br
.RI "\fIAn IPv4 address\&. \fP"
.ti -1c
.RI "class \fBIPAddressArg\fP"
.br
.RI "\fIParser class for IPv4 addresses\&. \fP"
.ti -1c
.RI "class \fBIPPrefixArg\fP"
.br
.RI "\fIParser class for IPv4 prefixes\&. \fP"
.ti -1c
.RI "class \fBIPPortArg\fP"
.br
.RI "\fIParser class for TCP/UDP ports\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBStringAccum\fP & \fBoperator<<\fP (\fBStringAccum\fP &, \fBIPAddress\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBArgContext\fP \fBblank_args\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBIPAddress\fP type for IPv4 addresses\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
