.TH "is_reference< T >" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
is_reference< T > \- Template determining whether T is a reference type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <type_traits\&.hh>\fP
.PP
Inherits \fBfalse_type\fP\&.
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class is_reference< T >"
Template determining whether T is a reference type\&. 

is_reference<T> is equivalent to \fBtrue_type\fP if T is a reference type (T& or T&&), \fBfalse_type\fP if it is not\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
