.TH "less< T >" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
less< T > \- Function object that encapsulates \fBoperator<()\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <algorithm\&.hh>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef T \fBfirst_argument_type\fP"
.br
.ti -1c
.RI "typedef T \fBsecond_argument_type\fP"
.br
.ti -1c
.RI "typedef bool \fBresult_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const T &x, const T &y)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
struct less< T >"
Function object that encapsulates \fBoperator<()\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
