.TH "include/click/list.hh" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/click/list.hh \- Click's doubly-linked list container template\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBList_member< T >\fP"
.br
.RI "\fIMember of classes to be placed on a \fBList\fP\&. \fP"
.ti -1c
.RI "class \fBList< T, member >\fP"
.br
.RI "\fIDoubly-linked list template\&. \fP"
.ti -1c
.RI "class \fBList_member< T >\fP"
.br
.RI "\fIMember of classes to be placed on a \fBList\fP\&. \fP"
.ti -1c
.RI "class \fBList< T, member >\fP"
.br
.RI "\fIDoubly-linked list template\&. \fP"
.ti -1c
.RI "class \fBList< T, member >::const_iterator\fP"
.br
.RI "\fIConst iterator type for \fBList\fP\&. \fP"
.ti -1c
.RI "class \fBList< T, member >::iterator\fP"
.br
.RI "\fIIterator type for \fBList\fP\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLIST_HEAD_MARKER\fP   0 /* ((T *) 1) */"
.br
.in -1c
.SH "Detailed Description"
.PP 
Click's doubly-linked list container template\&. 

> 
.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
