.TH "make_signed< T >" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
make_signed< T > \- Signed integer type transformation\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <type_traits\&.hh>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBinteger_traits\fP< T >::signed_type \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class make_signed< T >"
Signed integer type transformation\&. 

Given an integer type T, the type make_signed<T>::type is the signed version of T\&.
.PP
\fBSee also:\fP
.RS 4
\fBinteger_traits\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
