.TH "make_unsigned< T >" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
make_unsigned< T > \- Unsigned integer type transformation\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <type_traits\&.hh>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBinteger_traits\fP< T >::unsigned_type \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class make_unsigned< T >"
Unsigned integer type transformation\&. 

Given an integer type T, the type make_unsigned<T>::type is the unsigned version of T\&.
.PP
\fBSee also:\fP
.RS 4
\fBinteger_traits\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
