.TH "include/click/nameinfo.hh" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/click/nameinfo.hh \- Click databases for names, such as IP addresses and services\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <click/args\&.hh>\fP
.br
\fC#include <click/straccum\&.hh>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNameInfo\fP"
.br
.RI "\fIManages Click name databases\&. \fP"
.ti -1c
.RI "class \fBNameDB\fP"
.br
.RI "\fISuperclass for databases mapping names to values\&. \fP"
.ti -1c
.RI "class \fBStaticNameDB\fP"
.br
.RI "\fIA fixed database mapping names to 4-byte integer values\&. \fP"
.ti -1c
.RI "class \fBDynamicNameDB\fP"
.br
.RI "\fIA modifiable database mapping names to arbitrary values\&. \fP"
.ti -1c
.RI "class \fBNamedIntArg\fP"
.br
.RI "\fIParser class for named integers\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Click databases for names, such as IP addresses and services\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
