.TH "include/click/notifier.hh" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/click/notifier.hh \- Support for activity signals\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <click/task\&.hh>\fP
.br
\fC#include <click/atomic\&.hh>\fP
.br
\fC#include <click/algorithm\&.hh>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNotifierSignal\fP"
.br
.RI "\fIAn activity signal\&. \fP"
.ti -1c
.RI "class \fBNotifier\fP"
.br
.RI "\fIA basic activity signal and notification provider\&. \fP"
.ti -1c
.RI "class \fBActiveNotifier\fP"
.br
.RI "\fIA basic activity signal and notification provider that can reschedule any dependent \fBTask\fP objects\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBclick_swap\fP (\fBNotifierSignal\fP &x, \fBNotifierSignal\fP &y)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Support for activity signals\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
