.TH "NumArg" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumArg \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <args\&.hh>\fP
.PP
Inherited by \fBBandwidthArg\fP, \fBDecimalFixedPointArg\fP, \fBDoubleArg\fP, \fBFixedPointArg\fP, \fBIntArg\fP, and \fBSecondsArg\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBstatus_ok\fP = 0, \fBstatus_inval\fP = EINVAL, \fBstatus_range\fP = ERANGE, \fBstatus_notsup\fP, \fBstatus_unitless\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
never 

.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
