.TH "include/click/packet.hh" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/click/packet.hh \- The \fBPacket\fP class models packets in Click\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <click/ipaddress\&.hh>\fP
.br
\fC#include <click/glue\&.hh>\fP
.br
\fC#include <click/timestamp\&.hh>\fP
.br
\fC#include <click/skbmgr\&.hh>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPacket\fP"
.br
.RI "\fIA network packet\&. \fP"
.ti -1c
.RI "class \fBWritablePacket\fP"
.br
.RI "\fIA network packet believed not to be shared\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHAVE_CLICK_PACKET_POOL\fP   1"
.br
.ti -1c
.RI "#define \fBCLICK_PACKET_DEPRECATED_ENUM\fP   CLICK_DEPRECATED_ENUM"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBPacket\fP class models packets in Click\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
