.TH "include/click/router.hh" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/click/router.hh \- The \fBRouter\fP class implementing a router configuration\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <click/element\&.hh>\fP
.br
\fC#include <click/timer\&.hh>\fP
.br
\fC#include <click/sync\&.hh>\fP
.br
\fC#include <click/task\&.hh>\fP
.br
\fC#include <click/standard/threadsched\&.hh>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRouter\fP"
.br
.RI "\fIA router configuration\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The \fBRouter\fP class implementing a router configuration\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
