.TH "include/click/routervisitor.hh" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/click/routervisitor.hh \- \fBRouter\fP configuration visitors for finding elements and ports\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <click/element\&.hh>\fP
.br
\fC#include <click/bitvector\&.hh>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRouterVisitor\fP"
.br
.RI "\fIBase class for router configuration visitors\&. \fP"
.ti -1c
.RI "class \fBElementTracker\fP"
.br
.RI "\fIBase class for router configuration visitors that collect elements\&. \fP"
.ti -1c
.RI "class \fBElementCastTracker\fP"
.br
.RI "\fI\fBRouter\fP configuration visitor that collects elements that match a certain cast\&. \fP"
.ti -1c
.RI "class \fBElementNeighborhoodTracker\fP"
.br
.RI "\fI\fBRouter\fP configuration visitor that collects close-by elements\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBRouter\fP configuration visitors for finding elements and ports\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
