.TH "include/click/routerthread.hh" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/click/routerthread.hh \- The \fBRouterThread\fP class implementing the Click driver loop\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <click/sync\&.hh>\fP
.br
\fC#include <click/vector\&.hh>\fP
.br
\fC#include <click/timerset\&.hh>\fP
.br
\fC#include <click/cxxprotect\&.h>\fP
.br
\fC#include <linux/sched\&.h>\fP
.br
\fC#include <click/cxxunprotect\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRouterThread\fP"
.br
.RI "\fIA set of Tasks scheduled on the same CPU\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The \fBRouterThread\fP class implementing the Click driver loop\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
