.TH "SilentErrorHandler" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SilentErrorHandler \- An \fBErrorHandler\fP that does not report messages\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <error\&.hh>\fP
.PP
Inherits \fBErrorHandler\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
An \fBErrorHandler\fP that does not report messages\&. 

Use \fBSilentErrorHandler\fP when an \fBErrorHandler\fP object is required, but error messages should not be printed\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
