.TH "include/click/timer.hh" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/click/timer.hh \- Support for \fBTimer\fP, which triggers execution at a given time\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <click/sync\&.hh>\fP
.br
\fC#include <click/glue\&.hh>\fP
.br
\fC#include <click/element\&.hh>\fP
.br
\fC#include <click/timestamp\&.hh>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTimer\fP"
.br
.RI "\fITriggers execution at a given time\&. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fBTimerCallback\fP) (\fBTimer\fP *timer, void *user_data)"
.br
.ti -1c
.RI "typedef TimerCallback \fBTimerHook\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Support for \fBTimer\fP, which triggers execution at a given time\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
