.TH "todo" 3 "Fri Mar 3 2017" "Version 2.0" "XSocket API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBGlobal \fBXgetaddrinfo\fP (const char *name, const char *service, const struct addrinfo *hints, struct addrinfo **pai)\fP" 1c
flesh out \fBXgetaddrinfo()\fP text 
.IP "\fBFile \fBXkeys\&.c\fP \fP" 1c
write docs  
.IP "\fBFile \fBXmsg\&.c\fP \fP" 1c
write msg api docs 
.PP

