.TH "TokenCounter" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TokenCounter \- Jiffy-based token counter\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <click/tokenbucket\&.hh>\fP
.SH "Detailed Description"
.PP 
Jiffy-based token counter\&. 

Equivalent to \fBTokenCounterX<TokenRate>\fP\&. 
.PP
\fBSee also:\fP
.RS 4
\fBTokenCounterX\fP, \fBTokenRate\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
