.TH "TokenRate" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TokenRate \- Jiffy-based token bucket rate\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <click/tokenbucket\&.hh>\fP
.SH "Detailed Description"
.PP 
Jiffy-based token bucket rate\&. 

never Equivalent to \fBTokenRateX<TokenBucketJiffyParameters<unsigned> >\fP\&. 
.PP
\fBSee also:\fP
.RS 4
\fBTokenRateX\fP, \fBTokenBucketJiffyParameters\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
