.TH "true_type" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
true_type \- Type wrapper for the constant true\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <type_traits\&.hh>\fP
.PP
Inherited by has_trivial_copy< char >, has_trivial_copy< char_array< S > >, has_trivial_copy< EtherAddress >, has_trivial_copy< int >, has_trivial_copy< IP6Address >, has_trivial_copy< IPAddress >, has_trivial_copy< long >, has_trivial_copy< short >, has_trivial_copy< signed char >, has_trivial_copy< T * >, has_trivial_copy< Timestamp >, has_trivial_copy< unsigned >, has_trivial_copy< unsigned char >, has_trivial_copy< unsigned long >, has_trivial_copy< unsigned short >, and is_reference< T & >\&.
.SH "Detailed Description"
.PP 
Type wrapper for the constant true\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
