.TH "xsocket/XdefaultInterface.c" 3 "Fri Mar 3 2017" "Version 2.0" "XSocket API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xsocket/XdefaultInterface.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <errno\&.h>\fP
.br
\fC#include 'Xsocket\&.h'\fP
.br
\fC#include 'Xinit\&.h'\fP
.br
\fC#include 'Xutil\&.h'\fP
.br
\fC#include 'dagaddr\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBXupdateDefaultInterface\fP (int sockfd, int interface)"
.br
.ti -1c
.RI "int \fBXdefaultInterface\fP (int sockfd)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int XdefaultInterface (int sockfd)"

.SS "int XupdateDefaultInterface (int sockfd, int interface)"

.SH "Author"
.PP 
Generated automatically by Doxygen for XSocket API from the source code\&.
