.TH "include/click/xiaheader.hh" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/click/xiaheader.hh \- The \fBPacket\fP class models packets in Click\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <click/string\&.hh>\fP
.br
\fC#include <click/glue\&.hh>\fP
.br
\fC#include <clicknet/xia\&.h>\fP
.br
\fC#include <click/packet\&.hh>\fP
.br
\fC#include <click/xiapath\&.hh>\fP
.br

.SH "Detailed Description"
.PP 
The \fBPacket\fP class models packets in Click\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
