.TH "include/click/xid.hh" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/click/xid.hh \- \fBXID\fP addresses\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <click/string\&.hh>\fP
.br
\fC#include <click/glue\&.hh>\fP
.br
\fC#include <clicknet/xia\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBXID\fP"
.br
.RI "\fI\fBXID\fP helper class\&. \fP"
.ti -1c
.RI "class \fBXIDArg\fP"
.br
.RI "\fIParser class for XIA addresses\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBStringAccum\fP & \fBoperator<<\fP (\fBStringAccum\fP &, const \fBXID\fP &)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBArgContext\fP \fBblank_args\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBXID\fP addresses\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
