.TH "XIDArg" 3 "Thu Oct 12 2017" "Click" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XIDArg \- Parser class for XIA addresses\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xid\&.hh>\fP
.PP
Inherited by DefaultArg< XID >\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBparse\fP (const \fBString\fP &str, \fBXID\fP &value, const \fBArgContext\fP &args=blank_args)"
.br
.ti -1c
.RI "static bool \fBparse\fP (const \fBString\fP &str, \fBArgs\fP &args, unsigned char *value)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Parser class for XIA addresses\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Click from the source code\&.
