.TH "xsocket/Xmsg.c" 3 "Fri Mar 3 2017" "Version 2.0" "XSocket API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xsocket/Xmsg.c \- \fBXrecvmsg()\fP, \fBXsendmsg()\fP - send/receive a message on a socket\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Xsocket\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "ssize_t \fBXrecvmsg\fP (int fd, struct msghdr *msg, int flags)"
.br
.ti -1c
.RI "ssize_t \fBXsendmsg\fP (int fd, const struct msghdr *msg, int flags)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBTodo\fP
.RS 4
write msg api docs 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "ssize_t Xrecvmsg (int fd, struct msghdr * msg, int flags)"

.SS "ssize_t Xsendmsg (int fd, const struct msghdr * msg, int flags)"

.SH "Author"
.PP 
Generated automatically by Doxygen for XSocket API from the source code\&.
