.TH "xsocket/XupdateDAG.c" 3 "Fri Mar 3 2017" "Version 2.0" "XSocket API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xsocket/XupdateDAG.c \- Implements \fBXreadLocalHostAddr()\fP  

.SH SYNOPSIS
.br
.PP
\fC#include <errno\&.h>\fP
.br
\fC#include 'Xsocket\&.h'\fP
.br
\fC#include 'Xinit\&.h'\fP
.br
\fC#include 'Xutil\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_RV_DAG_SIZE\fP   1024"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBXupdateDAG\fP (int sockfd, int interface, const char *rdag, const char *r4id)"
.br
.ti -1c
.RI "int \fBXupdateRV\fP (int sockfd, int interface)"
.br
.ti -1c
.RI "int \fBXreadLocalHostAddr\fP (int sockfd, char *localhostDAG, unsigned lenDAG, char *local4ID, unsigned len4ID)"
.br
.RI "\fIretrieve the DAG and 4ID associated with this socket\&. \fP"
.ti -1c
.RI "int \fBXisDualStackRouter\fP (int sockfd)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAX_RV_DAG_SIZE   1024"

.SH "Function Documentation"
.PP 
.SS "int XisDualStackRouter (int sockfd)"

.SS "int XreadLocalHostAddr (int sockfd, char * localhostDAG, unsigned lenDAG, char * local4ID, unsigned len4ID)"
The DAG and 4ID assigned by the XIA stack\&. This call retrieves them so that they can be used for creating DAGs or for other purposes in user applications\&.
.PP
\fBParameters:\fP
.RS 4
\fIsockfd\fP an Xsocket (may be of any type XSOCK_STREAM, etc\&.\&.\&.) 
.br
\fIlocalhostDAG\fP buffer to receive the default DAG for this host 
.br
\fIlenDAG\fP size of the localhostDAG buffer 
.br
\fIlocal4ID\fP buffer to receive 4ID for this host (if known) 
.br
\fIlen4ID\fP size of the 4ID buffer
.RE
.PP
\fBReturns:\fP
.RS 4
0 on success 
.PP
-1 on failure with errno set 
.RE
.PP

.SS "int XupdateDAG (int sockfd, int interface, const char * rdag, const char * r4id)"

.SS "int XupdateRV (int sockfd, int interface)"

.SH "Author"
.PP 
Generated automatically by Doxygen for XSocket API from the source code\&.
